Library/Library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView
from catalog import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views





urlpatterns = [

    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('signup/', views.signup, name='signup'),
    url('login/',auth_views.login, name='login'),
    path('signup/', views.signup, name='signup'),

    path('login', auth_views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('logout',auth_views.logout,{'next_page':'login'},name='logout'),
    url(r'^signup/$',views.signup, name='signup'),

  
    path('', RedirectView.as_view(url='/login/')),
] +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Library/catalog/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
#path('index/', views.index, name='index'),
    path('', views.index, name='index'),
     path('signup', views.signup, name='signup'),
     path('books/', views.BookListView.as_view(), name='books'),
     path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
     path('writers/', views.WriterListView.as_view(), name='writers'),
     path('writer/<int:pk>', views.WriterDetailView.as_view(), name='author-detail')
]

Library/catalog/models.py
# from audioop import reverse
from django.urls import reverse

from django.db import models
from datetime import date


class Country(models.Model):

    name = models.CharField(max_length=200,
                            help_text="Enter a the country's natural language (e.g. Egypt, UK, French, etc.)")

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    publishedAt = models.DateField(null=True, blank=True)

    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")

    country =  models.CharField(max_length=200,
                            help_text="Enter a the country's natural language (e.g. Egypt, UK, French, etc.)")

    link = models.CharField(max_length=200, help_text="Enter a link of the book")
    author = models.ForeignKey('Writer', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
          return reverse('book-detail', args=[str(self.id)])



class Writer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death= models.DateField('died', null=True, blank=True)
    contact = models.CharField(max_length=100)

    books = models.CharField(max_length=100, help_text="enter books here ")
    bio = models.ImageField(upload_to='pictures', blank=True)

    class Meta:
        ordering = ["first_name", "last_name"]

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return '{0}{1}'.format(self.first_name, self.last_name)

Library/catalog/views.py
from django.shortcuts import render
from .models import Book, Writer
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views import generic




def index(request):
    """
    View function for home page of site.
    """
   
    num_books=Book.objects.all().count(),
    num_writers=Writer.objects.count()  
    
    
    return render(
        request,
        'catalog/index.html',
      

       context={'num_books':num_books,'num_writers':num_writers},
    )

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request,user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'catalog/signup.html', {'form': form})

class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'  
    queryset = Book.objects.all()[:5]


class BookDetailView(generic.DetailView):
    model = Book

class WriterListView(generic.ListView):
    model = Writer
    context_object_name = 'writer_list'   
    queryset = Writer.objects.all()[:5] 
class WriterDetailView(generic.DetailView):
    model = Writer

Library/catalog/templates/base-generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  
</head>
<style>

    .navbar {
      overflow: hidden;
      background-color: rgb(71, 44, 12);
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
    }
    
    .navbar a {
      float: left;
      display: block;
      color: #dbd7b1f6;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-size: 17px;
    }
    
    .navbar a:hover {
      background: rgba(161, 125, 90, 0.404);
      color: rgb(252, 241, 241);
    }
  
  .signup,.login {
      position: relative;
      margin-top: 130px;
      margin-left: -100px;
      padding: 20px 20px 20px;
      width: 310px;
      background: rgba(163, 156, 129, 0.911);
      border-radius: 3px;
      opacity: .9;
      text-align: center;
      color: rgb(43, 26, 5);
      border-radius: 10px; 
      
  }

  .register {
        position: relative;
        margin-top: 100px;
        margin-left: 20%;
        padding: 20px 20px 20px;
        width: 310px;
        background: rgba(163, 156, 129, 0.911);
        border-radius: 3px;
        opacity: .9;
        text-align: center;
        color: rgb(43, 26, 5);
        border-radius: 10px; 
        
    
    }
  a{
      text-decoration: none;
  
  }
  input {
      width: 100%;
      padding: 12px 20px;
      margin: 8px 0;
      display: inline-block;
      border: 1px solid #ccc;
      border-radius: 4px;
      box-sizing: border-box;
      background-color:#dbd7b1f6;
      border-radius: 5px;
  }
  
  #btn{
  
      background-color:#462e19f6;
      color: aliceblue;
  }
  
  #btn:hover{
  
      background-color:#997f69f6;
      color: aliceblue;
  }
</style>

<body>

  <div class="container-fluid">
     

    <div class="row">
      <div class="col-sm-2">
    
      </div>
      <div class="col-sm-10 ">
      {% block content %}
      <div class="navbar" id="topbar">
        <a href="{% url 'index' %}">Home</a>
        <a href="{% url 'writers' %}">All Authors</a>
        <a href="{% url 'books' %}">All Books</a>
       
      </div>
      {% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

Library/catalog/templates/catalog/book_detail.html
<style>
    body{
   
   background-image: url("../../static/index2.jpg");
   background-repeat: no-repeat;
   background-size: 1324px 700px;
   
   }
   #continer{
     margin-top: 5%;
     margin-left:15%; 
     border-style: solid;
     border-color: rgb(117, 89, 53);
     width: 500px;
     text-align: center;
     border-radius: 10px;
     color: rgb(65, 43, 11)
   }
   #name{
     font-family: "Times New Roman", Georgia, serif; 
     font-weight: bold;
     margin-top: 10%;
     margin-left:15%; 
     width: 500px;
     text-align: center;
     color: rgb(83, 57, 17);
   }
   
   #foter{
     width: 100%;
     border-top: 2px solid  rgb(83, 57, 17);
     float: inherit;
     margin-top: 16%; 
     margin-left: -120px;
     padding: 20px;
   }
   img{
     margin-left: 20%;
   }
   #autherlist{
     color: rgb(83, 57, 17);
    margin-top: 15%;
   }
  </style>
{% extends "base-generic.html" %}

{% block content %}
<div class="navbar" id="topbar">
    <a href="{% url 'index' %}">Home</a>
    <a href="{% url 'writers' %}">All Authors</a>
    <a href="{% url 'books' %}">All Books</a>
    <a href="{% url 'login' %}">Logout</a>
  </div>
  <div id="autherlist">
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
<p><strong>Summary:</strong> {{ book.summary }}</p>

<p><strong>Language:</strong> {{ book.language }}</p>  


<div style="margin-left:20px;margin-top:20px">


{% for copy in book.bookinstance_set.all %}
<hr>
<p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
{% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
<p><strong>Imprint:</strong> {{copy.imprint}}</p>
<p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>

{% endfor %}
</div>
</div>
{% endblock %}

Library/catalog/templates/catalog/book_list.html
<style>
  body{
 
 background-image: url("../../static/index2.jpg");
 background-repeat: no-repeat;
 background-size: 1324px 700px;
 
 }
 #continer{
   margin-top: 5%;
   margin-left:15%; 
   border-style: solid;
   border-color: rgb(117, 89, 53);
   width: 500px;
   text-align: center;
   border-radius: 10px;
   color: rgb(65, 43, 11)
 }
 #name{
   font-family: "Times New Roman", Georgia, serif; 
   font-weight: bold;
   margin-top: 10%;
   margin-left:15%; 
   width: 500px;
   text-align: center;
   color: rgb(83, 57, 17);
 }
 
 #foter{
   width: 100%;
   border-top: 2px solid  rgb(83, 57, 17);
   float: inherit;
   margin-top: 16%; 
   margin-left: -120px;
   padding: 20px;
 }
 img{
   margin-left: 20%;
 }
 #autherlist{
   color: rgb(83, 57, 17);
  margin-top: 15%;
 }
</style>
{% extends "base-generic.html" %}

{% block content %}
<div class="navbar" id="topbar">
  <a href="{% url 'index' %}">Home</a>
  <a href="{% url 'writers' %}">All Authors</a>
  <a href="{% url 'books' %}">All Books</a>
  <a href="{% url 'login' %}">Logout</a>
</div>
<div id="autherlist">
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{book.get_absolute_url }}">{{ book.title }}</a> <br>{{book.author}}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
      </div>
    {% endif %}
{% endblock %}

Library/catalog/templates/catalog/index.html
<style>
   body{
  
  background-image: url("../../static/index2.jpg");
  background-repeat: no-repeat;
  background-size: 1324px 700px;
  
  }
  #continer{
    margin-top: 5%;
    margin-left:15%; 
    border-style: solid;
    border-color: rgb(117, 89, 53);
    width: 500px;
    text-align: center;
    border-radius: 10px;
    color: rgb(65, 43, 11)
  }
  #name{
    font-family: "Times New Roman", Georgia, serif; 
    font-weight: bold;
    margin-top: 10%;
    margin-left:15%; 
    width: 500px;
    text-align: center;
    color: rgb(83, 57, 17);
  }
  
  #foter{
    width: 100%;
    border-top: 2px solid  rgb(83, 57, 17);
    float: inherit;
    margin-top: 16%; 
    margin-left: -120px;
    padding: 20px;
  }
  img{
    margin-left: 20%;
  }
</style>
{% extends 'base-generic.html' %}
{% block content %}
<div class="navbar" id="topbar">
  <a href="{% url 'index' %}">Home</a>
  <a href="{% url 'writers' %}">All Authors</a>
  <a href="{% url 'books' %}">All Books</a>
  <a href="{% url 'login' %}">Logout</a>
</div>

<div id="name">
  <h1>Welcome {{ user.username }}</h1>
</div>
  <div id="continer">
<h2>Content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    
  </ul>
</div>
<div id="foter">
<img src="../../static/face.png" height="50" width="50" >
<img src="../../static/link.png" height="50" width="50" >
<img src="../../static/tw.png" height="50" width="50" >
</div>
{% endblock %}

Library/catalog/templates/catalog/signup.html
<style>
    body{
  
  background-image: url("../../static/back.jpg");
  background-repeat: no-repeat;
  background-size: 1324px 700px;
  
  }
  </style>



{% extends 'base-generic.html' %}

{% block content %}
<div class="navbar" id="topbar">
  
  <a href="{% url 'signup' %}">Register</a>
  <a href="{% url 'login' %}">Login</a>

</div>
<div class="register">
  <form method="post">
    {% csrf_token %}
    {% for field in form %}

      <p>
        {{ field.label_tag }}<br>
        
        {{ field }}
        
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}

      </p>
    {% endfor %}
  
    <p class="submit"><input type="submit" name="commit" value="Register" id="btn"></p>

  </form>
  </div>
{% endblock %}

Library/catalog/templates/catalog/writer_detail.html
<style>
  body{
 
 background-image: url("../../static/index2.jpg");
 background-repeat: no-repeat;
 background-size: 1324px 700px;
 
 }
 #continer{
   margin-top: 5%;
   margin-left:15%; 
   border-style: solid;
   border-color: rgb(117, 89, 53);
   width: 500px;
   text-align: center;
   border-radius: 10px;
   color: rgb(65, 43, 11)
 }
 #name{
   font-family: "Times New Roman", Georgia, serif; 
   font-weight: bold;
   margin-top: 10%;
   margin-left:15%; 
   width: 500px;
   text-align: center;
   color: rgb(83, 57, 17);
 }
 
 #foter{
   width: 100%;
   border-top: 2px solid  rgb(83, 57, 17);
   float: inherit;
   margin-top: 16%; 
   margin-left: -120px;
   padding: 20px;
 }
 img{
   margin-left: 20%;
 }
 #writerlist{
   color: rgb(83, 57, 17);
  margin-top: 10%;
 }
</style>
{% extends "base-generic.html" %}

{% block content %}
<div class="navbar" id="topbar">
  <a href="{% url 'index' %}">Home</a>
  <a href="{% url 'writers' %}">All Authors</a>
  <a href="{% url 'books' %}">All Books</a>
  <a href="{% url 'login' %}">Logout</a>
</div>
<div id="writerlist">
<h1>writer: {{ writer }} </h1>
<p>{{writer.date_of_birth}} - {% if writer.date_of_death %}{{writer.date_of_death}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Books</h4>

<dl>
{% for book in writer.book_set.all %}
  <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> {{book.bookinstance_set.all.count}}</dt>
  <dd>{{book.summary}}</dd>
{% endfor %}
</dl>

</div>
</div>
{% endblock %}

Library/catalog/templates/catalog/writer_list.html
<style>
  body{
 
 background-image: url("../../static/index2.jpg");
 background-repeat: no-repeat;
 background-size: 1324px 700px;
 
 }
 #continer{
   margin-top: 5%;
   margin-left:15%; 
   border-style: solid;
   border-color: rgb(117, 89, 53);
   width: 500px;
   text-align: center;
   border-radius: 10px;
   color: rgb(65, 43, 11)
 }
 #name{
   font-family: "Times New Roman", Georgia, serif; 
   font-weight: bold;
   margin-top: 10%;
   margin-left:15%; 
   width: 500px;
   text-align: center;
   color: rgb(83, 57, 17);
 }
 
 #foter{
   width: 100%;
   border-top: 2px solid  rgb(83, 57, 17);
   float: inherit;
   margin-top: 16%; 
   margin-left: -120px;
   padding: 20px;
 }
 img{
   margin-left: 20%;
 }
 #autherlist{
   color: rgb(83, 57, 17);
  margin-top: 10%;
 }
</style>
{% extends "base-generic.html" %}

{% block content %}
<div class="navbar" id="topbar">
  <a href="{% url 'index' %}">Home</a>
  <a href="{% url 'writers' %}">All Authors</a>
  <a href="{% url 'books' %}">All Books</a>
  <a href="{% url 'login' %}">Logout</a>
</div>
<div id="autherlist">
<h1>Author List</h1>

{% if writer_list %}
  <ul>

  {% for author in writer_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">
      {{ author }} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %})
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>There are no authors available.</p>
{% endif %}
</div>
        
        
{% endblock %}